{% set name = "jsonrpcserver" %}
{% set version = "5.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0fdd69c15e67004fb064d2254469cf82d02b7bc8a7bf7760055caa9d62d92f7c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - oslash <1
    - jsonschema <4

test:
  imports:
    - jsonrpcserver

about:
  home: https://github.com/explodinglabs/jsonrpcserver
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Process JSON-RPC requests in Python.
  doc_url: https://www.jsonrpcserver.com/
  dev_url: https://github.com/explodinglabs/jsonrpcserver

extra:
  recipe-maintainers:
    - bcb
