{% set name = "jsonrpcserver" %}
{% set version = "5.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b15d3fd043ad0c40b2ff17f7df2ddaec2e880bb923b40d133939a107c97fde5c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - oslash <1
    - jsonschema <4

test:
  requires:
    - python {{ python_min }}
  imports:
    - jsonrpcserver

about:
  home: https://github.com/explodinglabs/jsonrpcserver
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Process JSON-RPC requests in Python.
  doc_url: https://www.jsonrpcserver.com/
  dev_url: https://github.com/explodinglabs/jsonrpcserver

extra:
  recipe-maintainers:
    - bcb
