travis:
  secure:
    BINSTAR_TOKEN: FO1PaVuI6wY83lCwqxgd3dUDvQeJ2bMYylmhtThAJdpiJROOpsLeTCus4ekLUZXW2yALq/NqBVt3VQYKhUyr8f95t9snEb6dZyvX4B/UgN+TTg89SgfwHh+TD0znjgh5jXGqGbYdk9wl29b9gDhtG992BForPMVylBOXXxG37K9DFgQX35Nga51q8ZXfxvJfnNkvig3LT0KSeQGTvewouKzk9wE/EF45QcI4f3fLwVcjBR0khT7z2fFgRTt7ekwRP6SCvYaw0B1yiyfxILoH46gd+L5s0xBm/77/++JPzlmpE3Vb1v1fhKXTQxvNq3o0382JhKbHVJA7w9taAKRzsrIop/g+NGfs6TD5ShV7Z4i7VeaTJHb0/F1/XDwLud7DAcL4qQTGYdOkUePl7Q7PszsSAVspo5PtOYNZZlFvGkjVvL8eFkKBEF9bWNvEUBnTFTefN6d48cleA0X8i5C7h3T49sSKICjWTVUXPK6OKZciEWcryTboOJ1PLESRibsjzAn5yD/+DTviRx4hXJY/e43DdN8+nn7dRkHzrLXcZZWu7Jh0qlrxlW5b6sh7JBAM+3AZwphZ6K6SNT9v/7n/+sFa2MJ3erSgYDthDNVMRmwtfe9lpKyNLBSIkYmS3tSUeTT6dXjEC5rVv4zcCvqKsPjYFmrWEMaoFUxSskbT+Pg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
