travis:
  secure:
    BINSTAR_TOKEN: A0XDY+3jeSLV/1lQMKWUYcN9RRuvH7p3alG/1V5rFaQjHQcodqRKGBdMuj872VtpvuFwOJ8A+aOTelkRO6Ar9dec1EFmtmnpoi2u9fu3OTPIVPEXkIU6DaHALbW+5i8Mkg7Km31rzTBO7ncJBDOKYxa283QOUUdY+FyFudmacm1Y2Yixavqx302+Uxlg52eo6BkHh67iIsDXz0RHcwVvXboSPVM4I+gWjpObqdQt4yE8qInHQvPRf6PTG/Sguku68Gt3pTdoepm9gAJ+vJ2GMiMFG5rgFmQsDTdST4zpSvfDvN7GAv8ceZOPiES2Ha3D8w6LxCeaSOLCOW8hBMv3cbOVARZcmY9ss4PDbnrTKpVK5WJLXbT3IA5rmvAFu4IbAUshZvlTN7uO93i+R7/c7SPytF7tjm107LqUlFs+Xyr/499NlWjHPouHM7N9y14UwHJFPsMT/I8Ub3KyLaTd7r6VBemRvSua9QtOovypnIR6FPbz743vmVYGkE0nHwHqZHC1Bwzt1y1OMOwdAk85o80J3KAelVMzu651pWCW32cJ9e9H3dchFoPUYjDRAoaiggrp0c1XwM4TiG3oEWHTDtKsRp+JbkpR96n9MOzq0nquhUilqAQbJ/53PyCLbo8GvFitIDP3EQwVI6XadWzVlTFfUXwn1v1W8YXP6n1A8DA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
